### ISSUE TITLE
Center color ignore fails on iOS 

### ISSUE THREAD

**Issue by candidodmv** [skordesign/SKOR.UI#5]
caused by following line

https://github.com/skordesign/SKOR.UI/blob/6d67baf82914d64d9435c2b5085dd234b9eb500e/Controls.iOS/Extensions/BackgroundExtension.cs#L15

I did fix that using the following condition:
```
...
if (centerColor.ToColor() != Color.Transparent)
...
```

**Comment by Alextorres950325** [comment]
yeah, I have the same issue with IOs, please fix that

**Comment by Alextorres950325** [comment]
> caused by following line
> 
> [SKOR.UI/Controls.iOS/Extensions/BackgroundExtension.cs](https://github.com/skordesign/SKOR.UI/blob/6d67baf82914d64d9435c2b5085dd234b9eb500e/Controls.iOS/Extensions/BackgroundExtension.cs#L15)
> 
> Line 15 in [6d67baf](/skordesign/SKOR.UI/commit/6d67baf82914d64d9435c2b5085dd234b9eb500e)
> 
>  if (centerColor != Color.Transparent.ToUIColor()) 
> I did fix that using the following condition:
> 
> ```
> ...
> if (centerColor.ToColor() != Color.Transparent)
> ...
> ```

How override this?

**Comment by candidodmv** [comment]
@Alextorres950325 that`s fixed. please verify

**Comment by Alextorres950325** [comment]
> @Alextorres950325 that`s fixed. please verify

yeah, the last pre-release version fix that issue. Thanks
